apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: geai1he25-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/geai1he25-java-springboot-gitops